//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rage.Addservice.Host.TwitterWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", ConfigurationName="TwitterWS.TwitterWSPortType")]
    public interface TwitterWSPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getTweetResponseList", ReplyAction="urn:getTweetResponseListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Rage.Addservice.Host.TwitterWS.getTweetResponseListResponse getTweetResponseList(Rage.Addservice.Host.TwitterWS.getTweetResponseListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getTweetList", ReplyAction="urn:getTweetListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Rage.Addservice.Host.TwitterWS.getTweetListResponse getTweetList(Rage.Addservice.Host.TwitterWS.getTweetListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getTimeline", ReplyAction="urn:getTimelineResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Rage.Addservice.Host.TwitterWS.getTimelineResponse getTimeline(Rage.Addservice.Host.TwitterWS.getTimelineRequest request);
        
        // CODEGEN: Parameter 'msg' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendMsg", ReplyAction="urn:sendMsgResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Rage.Addservice.Host.TwitterWS.sendMsgResponse sendMsg(Rage.Addservice.Host.TwitterWS.sendMsgRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getSubscribeUserList", ReplyAction="urn:getSubscribeUserListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Rage.Addservice.Host.TwitterWS.getSubscribeUserListResponse getSubscribeUserList(Rage.Addservice.Host.TwitterWS.getSubscribeUserListRequest request);
        
        // CODEGEN: Parameter 'url' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:addImageToTweet", ReplyAction="urn:addImageToTweetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Rage.Addservice.Host.TwitterWS.addImageToTweetResponse addImageToTweet(Rage.Addservice.Host.TwitterWS.addImageToTweetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTweetResponseList", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class getTweetResponseListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        public int id;
        
        public getTweetResponseListRequest() {
        }
        
        public getTweetResponseListRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTweetResponseListResponse", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class getTweetResponseListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public getTweetResponseListResponse() {
        }
        
        public getTweetResponseListResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTweetList", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class getTweetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        public int id;
        
        public getTweetListRequest() {
        }
        
        public getTweetListRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTweetListResponse", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class getTweetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public getTweetListResponse() {
        }
        
        public getTweetListResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimeline", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class getTimelineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        public int id;
        
        public getTimelineRequest() {
        }
        
        public getTimelineRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimelineResponse", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class getTimelineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public getTimelineResponse() {
        }
        
        public getTimelineResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMsg", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class sendMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string msg;
        
        public sendMsgRequest() {
        }
        
        public sendMsgRequest(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMsgResponse", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class sendMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        public bool @return;
        
        public sendMsgResponse() {
        }
        
        public sendMsgResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.adcamptwitter.pk.pl/xsd")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailAddressField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string loginField;
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://net.java/xsd")]
    public partial class URL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authorityField;
        
        private object contentField;
        
        private int defaultPortField;
        
        private bool defaultPortFieldSpecified;
        
        private string fileField;
        
        private string hostField;
        
        private string pathField;
        
        private int portField;
        
        private bool portFieldSpecified;
        
        private string protocolField;
        
        private string queryField;
        
        private string refField;
        
        private string userInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
                this.RaisePropertyChanged("authority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public object content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int defaultPort {
            get {
                return this.defaultPortField;
            }
            set {
                this.defaultPortField = value;
                this.RaisePropertyChanged("defaultPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultPortSpecified {
            get {
                return this.defaultPortFieldSpecified;
            }
            set {
                this.defaultPortFieldSpecified = value;
                this.RaisePropertyChanged("defaultPortSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
                this.RaisePropertyChanged("file");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
                this.RaisePropertyChanged("host");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
                this.RaisePropertyChanged("port");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool portSpecified {
            get {
                return this.portFieldSpecified;
            }
            set {
                this.portFieldSpecified = value;
                this.RaisePropertyChanged("portSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
                this.RaisePropertyChanged("protocol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
                this.RaisePropertyChanged("ref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string userInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
                this.RaisePropertyChanged("userInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubscribeUserList", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class getSubscribeUserListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        public int id;
        
        public getSubscribeUserListRequest() {
        }
        
        public getSubscribeUserListRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubscribeUserListResponse", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class getSubscribeUserListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public User[] @return;
        
        public getSubscribeUserListResponse() {
        }
        
        public getSubscribeUserListResponse(User[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addImageToTweet", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class addImageToTweetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Rage.Addservice.Host.TwitterWS.URL url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=1)]
        public int id;
        
        public addImageToTweetRequest() {
        }
        
        public addImageToTweetRequest(Rage.Addservice.Host.TwitterWS.URL url, int id) {
            this.url = url;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addImageToTweetResponse", WrapperNamespace="http://twitter.ws.server.adcamptwitter.pk.pl", IsWrapped=true)]
    public partial class addImageToTweetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://twitter.ws.server.adcamptwitter.pk.pl", Order=0)]
        public bool @return;
        
        public addImageToTweetResponse() {
        }
        
        public addImageToTweetResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TwitterWSPortTypeChannel : Rage.Addservice.Host.TwitterWS.TwitterWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TwitterWSPortTypeClient : System.ServiceModel.ClientBase<Rage.Addservice.Host.TwitterWS.TwitterWSPortType>, Rage.Addservice.Host.TwitterWS.TwitterWSPortType {
        
        public TwitterWSPortTypeClient() {
        }
        
        public TwitterWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TwitterWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwitterWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwitterWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rage.Addservice.Host.TwitterWS.getTweetResponseListResponse Rage.Addservice.Host.TwitterWS.TwitterWSPortType.getTweetResponseList(Rage.Addservice.Host.TwitterWS.getTweetResponseListRequest request) {
            return base.Channel.getTweetResponseList(request);
        }
        
        public string[] getTweetResponseList(int id) {
            Rage.Addservice.Host.TwitterWS.getTweetResponseListRequest inValue = new Rage.Addservice.Host.TwitterWS.getTweetResponseListRequest();
            inValue.id = id;
            Rage.Addservice.Host.TwitterWS.getTweetResponseListResponse retVal = ((Rage.Addservice.Host.TwitterWS.TwitterWSPortType)(this)).getTweetResponseList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rage.Addservice.Host.TwitterWS.getTweetListResponse Rage.Addservice.Host.TwitterWS.TwitterWSPortType.getTweetList(Rage.Addservice.Host.TwitterWS.getTweetListRequest request) {
            return base.Channel.getTweetList(request);
        }
        
        public string[] getTweetList(int id) {
            Rage.Addservice.Host.TwitterWS.getTweetListRequest inValue = new Rage.Addservice.Host.TwitterWS.getTweetListRequest();
            inValue.id = id;
            Rage.Addservice.Host.TwitterWS.getTweetListResponse retVal = ((Rage.Addservice.Host.TwitterWS.TwitterWSPortType)(this)).getTweetList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rage.Addservice.Host.TwitterWS.getTimelineResponse Rage.Addservice.Host.TwitterWS.TwitterWSPortType.getTimeline(Rage.Addservice.Host.TwitterWS.getTimelineRequest request) {
            return base.Channel.getTimeline(request);
        }
        
        public string[] getTimeline(int id) {
            Rage.Addservice.Host.TwitterWS.getTimelineRequest inValue = new Rage.Addservice.Host.TwitterWS.getTimelineRequest();
            inValue.id = id;
            Rage.Addservice.Host.TwitterWS.getTimelineResponse retVal = ((Rage.Addservice.Host.TwitterWS.TwitterWSPortType)(this)).getTimeline(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rage.Addservice.Host.TwitterWS.sendMsgResponse Rage.Addservice.Host.TwitterWS.TwitterWSPortType.sendMsg(Rage.Addservice.Host.TwitterWS.sendMsgRequest request) {
            return base.Channel.sendMsg(request);
        }
        
        public bool sendMsg(string msg) {
            Rage.Addservice.Host.TwitterWS.sendMsgRequest inValue = new Rage.Addservice.Host.TwitterWS.sendMsgRequest();
            inValue.msg = msg;
            Rage.Addservice.Host.TwitterWS.sendMsgResponse retVal = ((Rage.Addservice.Host.TwitterWS.TwitterWSPortType)(this)).sendMsg(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rage.Addservice.Host.TwitterWS.getSubscribeUserListResponse Rage.Addservice.Host.TwitterWS.TwitterWSPortType.getSubscribeUserList(Rage.Addservice.Host.TwitterWS.getSubscribeUserListRequest request) {
            return base.Channel.getSubscribeUserList(request);
        }
        
        public User[] getSubscribeUserList(int id) {
            Rage.Addservice.Host.TwitterWS.getSubscribeUserListRequest inValue = new Rage.Addservice.Host.TwitterWS.getSubscribeUserListRequest();
            inValue.id = id;
            Rage.Addservice.Host.TwitterWS.getSubscribeUserListResponse retVal = ((Rage.Addservice.Host.TwitterWS.TwitterWSPortType)(this)).getSubscribeUserList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rage.Addservice.Host.TwitterWS.addImageToTweetResponse Rage.Addservice.Host.TwitterWS.TwitterWSPortType.addImageToTweet(Rage.Addservice.Host.TwitterWS.addImageToTweetRequest request) {
            return base.Channel.addImageToTweet(request);
        }
        
        public bool addImageToTweet(Rage.Addservice.Host.TwitterWS.URL url, int id) {
            Rage.Addservice.Host.TwitterWS.addImageToTweetRequest inValue = new Rage.Addservice.Host.TwitterWS.addImageToTweetRequest();
            inValue.url = url;
            inValue.id = id;
            Rage.Addservice.Host.TwitterWS.addImageToTweetResponse retVal = ((Rage.Addservice.Host.TwitterWS.TwitterWSPortType)(this)).addImageToTweet(inValue);
            return retVal.@return;
        }
    }
}
